dependencies:
  # - openssl
  # - libyaml
  # - postgresql
  # - postgresql-libs
  # - postgresql-devel
  # - mysql-libs
  # - mysql-devel
  # - readline-devel
  # - ncurses-devel
  # - xz-devel
  # - libxml2-devel
  # - libgpg-error-devel
  # - libgcrypt-devel
  # - libxslt-devel
  # - libevent-devel
  # - sqlite-devel
  # - ImageMagick
  # - ImageMagick-devel
  # - libicu
  # - libuv
  # - npm
  # - nodejs
targets:
  ubuntu-12.04:
  ubuntu-14.04:
  centos-7:
    dependencies:
      # - openssl
      # - libyaml
      # - postgresql
      # - postgresql-libs
      # - postgresql-devel
      # - mariadb-libs
      # - mariadb-devel
      # - readline-devel
      # - ncurses-devel
      # - xz-devel
      # - libxml2-devel
      # - libgpg-error-devel
      # - libgcrypt-devel
      # - libxslt-devel
      # - libevent-devel
      # - sqlite-devel
      # - ImageMagick
      # - ImageMagick-devel
      # - libicu
      # - libuv
      # - npm
      # - nodejs
    build_dependencies:
      # - openssl
      # - libyaml
      # - postgresql
      # - postgresql-libs
      # - postgresql-devel
      # - mariadb-libs
      # - mariadb-devel
      # - readline-devel
      # - ncurses-devel
      # - xz-devel
      # - libxml2-devel
      # - libgpg-error-devel
      # - libgcrypt-devel
      # - libxslt-devel
      # - libevent-devel
      # - sqlite-devel
      # - ImageMagick
      # - ImageMagick-devel
      # - libicu
      # - libuv
      # - npm
      # - nodejs 
build_dependencies:
  # - openssl
  # - libyaml
  # - postgresql
  # - postgresql-libs
  # - postgresql-devel
  # - mariadb-libs
  # - mariadb-devel
  # - readline-devel
  # - ncurses-devel
  # - xz-devel
  # - libxml2-devel
  # - libgpg-error-devel
  # - libgcrypt-devel
  # - libxslt-devel
  # - libevent-devel
  # - sqlite-devel
  # - ImageMagick
  # - ImageMagick-devel
  # - libicu
  # - libuv
  # - npm
  # - nodejs 

  # - openssl-1.0.1e-51.el7_2.7.rpm
  # - libyaml-0.1.4-11.el7_0.rpm
  # - postgresql-9.2.15-1.el7_2.rpm
  # - postgresql-libs-9.2.15-1.el7_2.rpm
  # - postgresql-devel-9.2.15-1.el7_2.rpm
  # - mariadb-libs-5.5.50-1.el7_2.rpm
  # - mariadb-devel-5.5.50-1.el7_2.rpm
  # - readline-devel-6.2-9.el7.rpm
  # - ncurses-devel-5.9-13.20130511.el7.rpm
  # - xz-devel-5.1.2-12alpha.el7.rpm
  # - libxml2-devel-2.9.1-6.el7_2.3.rpm
  # - libgpg-error-devel-1.12-3.el7.rpm
  # - libgcrypt-devel-1.5.3-12.el7_1.1.rpm
  # - libxslt-devel-1.1.28-5.el7.rpm
  # - libevent-devel-2.0.21-4.el7.rpm
  # - sqlite-devel-3.7.17-8.el7.rpm
  # - ImageMagick-6.7.8.9-15.el7_2.rpm
  # - ImageMagick-devel-6.7.8.9-15.el7_2.rpm
  # - libicu-50.1.2-15.el7.x86_64.rpm
  # - libuv-1.9.1-1.el7.x86_64.rpm
  # - npm-3.10.3-107.el7.x86_64.rpm
  # - nodejs-6.7.0-107.el7.x86_64.rpm  


















  # - openssl-1.0.1e-51.el7_2.7.rpm
  # - libyaml-0.1.4-11.el7_0.rpm
  # - postgresql-9.2.15-1.el7_2.rpm
  # - postgresql-libs-9.2.15-1.el7_2.rpm
  # - postgresql-devel-9.2.15-1.el7_2.rpm
  # - mariadb-libs-5.5.50-1.el7_2.rpm
  # - mariadb-devel-5.5.50-1.el7_2.rpm
  # - readline-devel-6.2-9.el7.rpm
  # - ncurses-devel-5.9-13.20130511.el7.rpm
  # - xz-devel-5.1.2-12alpha.el7.rpm
  # - libxml2-devel-2.9.1-6.el7_2.3.rpm
  # - libgpg-error-devel-1.12-3.el7.rpm
  # - libgcrypt-devel-1.5.3-12.el7_1.1.rpm
  # - libxslt-devel-1.1.28-5.el7.rpm
  # - libevent-devel-2.0.21-4.el7.rpm
  # - sqlite-devel-3.7.17-8.el7.rpm  
  # - fontconfig-2.10.95-7.el7.rpm
  # - fontpackages-filesystem-1.44-8.el7.rpm
  # - cairo-1.14.2-1.el7.rpm
  # - freetype-2.4.11-11.el7.rpm
  # - OpenEXR-libs-1.7.1-7.el7.rpm
  # - cups-libs-1.6.3-22.el7.rpm
  # - ghostscript-fonts-5.50-32.el7.rpm
  # - graphite2-1.3.6-1.el7_2.rpm
  # - harfbuzz-0.9.36-1.el7.rpm
  # - gdk-pixbuf2-2.31.6-3.el7.rpm
  # - ilmbase-1.0.3-7.el7.rpm
  # - ghostscript-9.07-18.el7.rpm
  # - jbigkit-libs-2.0-11.el7.rpm
  # - libICE-1.0.9-2.el7.rpm
  # - libSM-1.2.2-2.el7.rpm
  # - libX11-1.6.3-2.el7.rpm
  # - libX11-common-1.6.3-2.el7.rpm
  # - libXau-1.0.8-2.1.el7.rpm
  # - jasper-libs-1.900.1-29.el7.rpm
  # - libXdamage-1.1.4-4.1.el7.rpm
  # - libXext-1.3.3-3.el7.rpm
  # - libXft-2.3.2-2.el7.rpm
  # - libXfont-1.5.1-2.el7.rpm
  # - libXrender-0.9.8-2.1.el7.rpm
  # - libXxf86vm-1.1.3-2.1.el7.rpm
  # - libXfixes-5.0.1-2.1.el7.rpm
  # - libdrm-2.4.60-3.el7.rpm
  # - libjpeg-turbo-1.2.90-5.el7.rpm
  # - libfontenc-1.1.2-3.el7.rpm
  # - libpciaccess-0.13.4-2.el7.rpm
  # - lcms2-2.6-2.el7.rpm
  # - librsvg2-2.39.0-1.el7.rpm
  # - libXt-1.1.4-6.1.el7.rpm
  # - libpng-1.5.13-7.el7_2.rpm
  # - libwmf-lite-0.2.8.4-41.el7_1.rpm
  # - libxcb-1.11-4.el7.rpm
  # - libxshmfence-1.2-1.el7.rpm
  # - hwdata-0.252-8.1.el7.rpm
  # - mesa-libEGL-10.6.5-3.20150824.el7.rpm
  # - mesa-libgbm-10.6.5-3.20150824.el7.rpm
  # - libthai-0.1.14-9.el7.rpm
  # - mesa-libglapi-10.6.5-3.20150824.el7.rpm
  # - mesa-libGL-10.6.5-3.20150824.el7.rpm
  # - libtiff-4.0.3-25.el7_2.rpm
  # - pixman-0.32.6-3.el7.rpm
  # - xorg-x11-font-utils-7.5-20.el7.rpm
  # - poppler-data-0.4.6-3.el7.rpm
  # - libtool-ltdl-2.4.2-21.el7_2.rpm
  # - pango-1.36.8-2.el7.rpm
  # - urw-fonts-2.4-16.el7.rpm
  # - ImageMagick-6.7.8.9-15.el7_2.rpm
  # - xorg-x11-proto-devel-7.7-12.el7.rpm
  # - libICE-devel-1.0.9-2.el7.rpm
  # - libjpeg-turbo-devel-1.2.90-5.el7.rpm
  # - jasper-devel-1.900.1-29.el7.rpm
  # - libSM-devel-1.2.2-2.el7.rpm
  # - libXau-devel-1.0.8-2.1.el7.rpm
  # - libxcb-devel-1.11-4.el7.rpm
  # - libX11-devel-1.6.3-2.el7.rpm
  # - libXext-devel-1.3.3-3.el7.rpm
  # - libXt-devel-1.1.4-6.1.el7.rpm
  # - libtiff-devel-4.0.3-25.el7_2.rpm
  # - freetype-devel-2.4.11-11.el7.rpm
  # - ghostscript-devel-9.07-18.el7.rpm
  # - bzip2-devel-1.0.6-13.el7.rpm
  # - ImageMagick-devel-6.7.8.9-15.el7_2.rpm
  # - libicu-50.1.2-15.el7.x86_64.rpm
  # - libuv-1.9.1-1.el7.x86_64.rpm
  # - npm-3.10.3-107.el7.x86_64.rpm
  # - nodejs-6.7.0-107.el7.x86_64.rpm  